[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "scm"
tag_format = "v$version"
update_changelog_on_bump = true
major_version_zero = true
changelog_incremental = true
annotated_tag = true
